imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    translator:
        fallback: fr
    secret: %secret%
    router:
        resource: %kernel.root_dir%/config/routing.yml
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    templating:
        engines:
            - twig
    default_locale: fr
    trusted_proxies: ~
    session: ~
    fragments: ~
    http_method_override: true

twig:
    debug: %kernel.debug%
    strict_variables: %kernel.debug%

assetic:
    debug: %kernel.debug%
    use_controller: false
    bundles: [ ]
    filters:
        cssrewrite: ~

doctrine:
    dbal:
        driver: pdo_mysql
        host: 127.0.0.1
        port: ~
        dbname: bisouland
        user: %database_user%
        password: %database_password%
        charset: UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
