imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi: ~
    #translator: { fallback: %locale% }
    secret: %secret%
    http_method_override: true
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form: ~
    csrf_protection: ~
    validation:
        enable_annotations: true
    templating:
        engines: ['twig']
    default_locale: "%locale%"
    trusted_proxies: ~
    session:
        save_path: "%kernel.root_dir%/sessions/"
    fragments: ~

# Twig Configuration
twig:
    debug: %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - ':Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug: %kernel.debug%
    use_controller: false
    bundles: [ ]
    #java: /usr/bin/java
    filters:
        less:
           node: %less_bin%
           node_paths: %less_paths%
        cssrewrite: ~
        uglifyjs:
            bin: %uglifyjs_bin%
            compress: true
            mangle: true
        uglifycss:
            bin: %uglifycss_bin%

# Doctrine Configuration
doctrine:
    dbal:
        driver: %database_driver%
        host: %database_host%
        port: %database_port%
        dbname: %database_name%_%kernel.environment%
        user: %database_user%
        password: %database_password%
        charset: UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path: %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host: %mailer_host%
    username: %mailer_user%
    password: %mailer_password%
    spool: { type: memory }
    encryption:  %mailer_encryption%
    auth_mode:  %mailer_auth_mode%
    port:  %mailer_port%

# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Bisouland\UserBundle\Entity\User

    from_email:
        address: %email_expeditor%
        sender_name: Bisouland

    registration:
        form:
            type: bisouland_user_registration

# KnpMenuBundle Configuration
knp_menu:
    twig:
        template: BisoulandPreRegistrationBundle::menu.html.twig
