      <div class="section">
        <h2>Accueil</h2>

        <p>
          BisouLand est un jeu multijoueurs sur internet.<br />
          Pour jouer, il suffit de disposer d'un simple navigateur internet.<br />
          Rejoins la communauté !<br />
          Tu peux visiter la page d'aide pour apprendre les bases.<br />
        </p>

        <p>
          Ce site est en perpétuelle évolution, n'hésite donc pas à me signaler tout bug.
        </p>
      </div>

      <div class="section">
        <h2>Reprise de Bisouland</h2>

        <p>
          le 29/05/2011 à 22h56
        </p>

        <p>
          Bonjour à tous.<br />
          <br />
          Créé en 2005 et amélioré jusqu'en 2008 par Piwaï, Bisouland est désormais repris par sa communauté !<br />
          En effet, les perturbations observées la semaine dernières sont dus aux changements de serveur de Bisouland.<br />
          Concrètement, qu'est-ce qui change ?
        </p>

        <ol>
          <li>Techniquement, le code devient Open Source et les trois joueurs ZEAS, facepalm et cat_loic corrigeront les bugs et apporteront quelques modifications.</li>
          <li>Pour les joueurs : le jeu redeviendra plus actif et attractif, nous nous efforcerons de rendre Bisouland de plus en plus fun !</li>
        </ol>

        <p>
          Nous ferons en sorte que les changements ne soient pas trop perturbants (par exemple pas de sortie d'une version 2 qui change tout, plutôt des améliorations progressives).</br>
          En attendant, si vous avez des suggestions ou des bugs à rapporter, n'hésitez pas à envoyer un Message Privé à "admin".
        </p>

        <p>
          -- L'équipe Bisouland (ZEAS, facepalm et cat_loic).
        </p>
      </div>
