account_removal_confirmation:
    pattern: /account/removal_confirmation
    defaults:
        _controller: "BisoulandUserBundle:AccountRemoval:confirmation"
    methods: [GET, POST]

home:
    pattern: /
    defaults:
        _controller: "BisoulandPreRegistrationBundle:Default:index"
    methods: [GET]
