services:
    bisouland_pre_registration.builder:
        class: Bisouland\PreRegistrationBundle\Menu\Builder
        arguments: ["@knp_menu.factory", "@security.context"]

    bisouland_pre_registration.login:
        class: Knp\Menu\MenuItem
        factory_service: bisouland_pre_registration.builder
        factory_method: createLoginMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: login_menu }

    bisouland_pre_registration.user:
        class: Knp\Menu\MenuItem
        factory_service: bisouland_pre_registration.builder
        factory_method: createUserMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: user_menu }
