<?php

//Gestion des pages
$array_pages = array(
    "accueil" => "accueil.php",
    "inscription" => "inscription.php",
    "confirmation" => "confirmation.php",
    "connected" => "connected.php",
    "membres" => "membres.php",
    "erreurConnexion" => "erreurConnexion.php",
    "construction" => "construction.php",
    "bisous" => "bisous.php",
    "livreor" => "livreor.php",
    "aide" => "aide.php",
    "envoi" => "envoi.php",
    "lire" => "lire.php",
    "boite" => "boite.php",
    "techno" => "techno.php",
    "nuage" => "nuage.php",
    "infos" => "infos.php",
    "contact" => "contact.php",
    "action" => "action.php",
    "changepass" => "changepass.php",
    "cerveau" => "cerveau.php",
    "topten" => "topten.php",
    "stats" => "stats.php",
    "recherche" => "recherche.php",
    "connexion" => "connexion.php",
    "perdu" => "perdu.php",
    "newpass" => "newpass.php",
    "yeux" => "yeux.php",
    "faq" => "faq.php"
);

$array_titres = array(
    "accueil" => "Accueil",
    "inscription" => "Inscription",
    "confirmation" => "Confirmation",
    "connected" => "Mon compte",
    "membres" => "Membres",
    "erreurConnexion" => "Erreur de connexion",
    "construction" => "Organes",
    "bisous" => "Cr&eacute;er des bisous",
    "livreor" => "Livre d'or",
    "aide" => "Aide",
    "envoi" => "Envoyer un message",
    "lire" => "Lire un message",
    "boite" => "Messages priv&eacute;s",
    "techno" => "Techniques diverses et vari&eacute;es",
    "nuage" => "La tête dans les nuages...",
    "infos" => "Encyclop&eacute;die",
    "contact" => "Contact",
    "action" => "Action",
    "changepass" => "Changer votre mot de passe",
    "cerveau" => "Cerveau",
    "topten" => "Meilleurs Joueurs",
    "stats" => "Statistiques",
    "recherche" => "Recherche",
    "connexion" => "Connexion",
    "perdu" => "Mot de passe perdu",
    "newpass" => "Nouveau mot de passe",
    "yeux" => "D&eacute;visager un joueur",
    "faq" => "FAQ"
);
