<?php

define('DATABASE_HOST', $_ENV['DATABASE_HOST']);
define('DATABASE_USER', $_ENV['DATABASE_USER']);
define('DATABASE_PASSWORD', $_ENV['DATABASE_PASSWORD']);
define('DATABASE_NAME', $_ENV['DATABASE_NAME']);

define('EMAIL_ADMIN', $_ENV['EMAIL_ADMIN']);
define('EMAIL_EXPEDITOR', $_ENV['EMAIL_EXPEDITOR']);
